<?php

## FILE GENERATED BY MAGRATHEA.
## SHOULD NOT BE CHANGED MANUALLY

class ProjectBase extends MagratheaModel implements iMagratheaModel {

	public $id, $name, $image, $status_id, $start_date, $end_date;
	public $created_at, $updated_at;
	public $dbPk;
	protected $autoload = null;

	public function __construct(  $id=0  ){ 
		$this->MagratheaStart();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function MagratheaStart(){
		$this->dbTable = "projects";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["name"] = "string";
		$this->dbValues["image"] = "int";
		$this->dbValues["status_id"] = "int";
		$this->dbValues["start_date"] = "datetime";
		$this->dbValues["end_date"] = "datetime";

		$this->relations["properties"]["Status"] = null;
		$this->relations["methods"]["Status"] = "GetStatus";
		$this->relations["lazyload"]["Status"] = "false";
		$this->relations["properties"]["Tasks"] = null;
		$this->relations["methods"]["Tasks"] = "GetTasks";
		$this->relations["lazyload"]["Tasks"] = "true";
		$this->relations["properties"]["Works"] = null;
		$this->relations["methods"]["Works"] = "GetWorks";
		$this->relations["lazyload"]["Works"] = "true";

		$this->dbAlias["created_at"] =  "datetime";
		$this->dbAlias["updated_at"] =  "datetime";
	}

	// >>> relations:
	public function GetStatus(){
		if($this->relations["properties"]["Status"] != null) return $this->relations["properties"]["Status"];
		$this->relations["properties"]["Status"] = new Status($this->status_id);
		return $this->relations["properties"]["Status"];
	}
	public function SetStatus($status){
		$this->relations["properties"]["Status"] = $status;
		$this->status_id = $status->GetID();
		return $this;
	}
	public function GetTasks(){
		if($this->relations["properties"]["Tasks"] != null) return $this->relations["properties"]["Tasks"];
		$pk = $this->dbPk;
		$this->relations["properties"]["Tasks"] = TaskControlBase::GetWhere(array("project_id" => $this->$pk));
		return $this->relations["properties"]["Tasks"];
	}
	public function GetWorks(){
		if($this->relations["properties"]["Works"] != null) return $this->relations["properties"]["Works"];
		$pk = $this->dbPk;
		$this->relations["properties"]["Works"] = WorkControlBase::GetWhere(array("project_id" => $this->$pk));
		return $this->relations["properties"]["Works"];
	}

}

class ProjectControlBase extends MagratheaModelControl {
	protected static $modelName = "Project";
	protected static $dbTable = "projects";
}
?>