<?php

## FILE GENERATED BY MAGRATHEA.
## SHOULD NOT BE CHANGED MANUALLY

class StatusChangeBase extends MagratheaModel implements iMagratheaModel {

	public $id, $task_id, $old_status, $new_status, $timestamp;
	public $created_at, $updated_at;
	protected $autoload = null;

	public function __construct(  $id=0  ){ 
		$this->MagratheaStart();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function MagratheaStart(){
		$this->dbTable = "status_changes";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["task_id"] = "int";
		$this->dbValues["old_status"] = "int";
		$this->dbValues["new_status"] = "int";
		$this->dbValues["timestamp"] = "datetime";

		$this->relations["properties"]["OldStatus"] = null;
		$this->relations["methods"]["OldStatus"] = "GetOldStatus";
		$this->relations["lazyload"]["OldStatus"] = "false";
		$this->relations["properties"]["NewStatus"] = null;
		$this->relations["methods"]["NewStatus"] = "GetNewStatus";
		$this->relations["lazyload"]["NewStatus"] = "false";
		$this->relations["properties"]["Tasks"] = null;
		$this->relations["methods"]["Tasks"] = "GetTasks";
		$this->relations["lazyload"]["Tasks"] = "false";

		$this->dbAlias["created_at"] =  "datetime";
		$this->dbAlias["updated_at"] =  "datetime";
	}

	// >>> relations:
	public function GetOldStatus(){
		if($this->relations["properties"]["OldStatus"] != null) return $this->relations["properties"]["OldStatus"];
		$this->relations["properties"]["OldStatus"] = new Status($this->old_status);
		return $this->relations["properties"]["OldStatus"];
	}
	public function SetOldStatus($oldstatus){
		$this->relations["properties"]["OldStatus"] = $oldstatus;
		$this->old_status = $oldstatus->GetID();
		return $this;
	}
	public function GetNewStatus(){
		if($this->relations["properties"]["NewStatus"] != null) return $this->relations["properties"]["NewStatus"];
		$this->relations["properties"]["NewStatus"] = new Status($this->new_status);
		return $this->relations["properties"]["NewStatus"];
	}
	public function SetNewStatus($newstatus){
		$this->relations["properties"]["NewStatus"] = $newstatus;
		$this->new_status = $newstatus->GetID();
		return $this;
	}
	public function GetTasks(){
		if($this->relations["properties"]["Tasks"] != null) return $this->relations["properties"]["Tasks"];
		$this->relations["properties"]["Tasks"] = new Task($this->task_id);
		return $this->relations["properties"]["Tasks"];
	}
	public function SetTasks($tasks){
		$this->relations["properties"]["Tasks"] = $tasks;
		$this->task_id = $tasks->GetID();
		return $this;
	}

}

class StatusChangeControlBase extends MagratheaModelControl {
	protected static $modelName = "StatusChange";
	protected static $dbTable = "status_changes";
}
?>