<?php

## FILE GENERATED BY MAGRATHEA.
## SHOULD NOT BE CHANGED MANUALLY

class UserBase extends MagratheaModel implements iMagratheaModel {

	public $id, $name, $email, $password;
	public $created_at, $updated_at;
	protected $autoload = null;

	public function __construct(  $id=0  ){ 
		$this->MagratheaStart();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function MagratheaStart(){
		$this->dbTable = "users";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["name"] = "string";
		$this->dbValues["email"] = "string";
		$this->dbValues["password"] = "string";

		$this->relations["properties"]["Tasks"] = null;
		$this->relations["methods"]["Tasks"] = "GetTasks";
		$this->relations["lazyload"]["Tasks"] = "true";
		$this->relations["properties"]["CreatedTasks"] = null;
		$this->relations["methods"]["CreatedTasks"] = "GetCreatedTasks";
		$this->relations["lazyload"]["CreatedTasks"] = "true";
		$this->relations["properties"]["Works"] = null;
		$this->relations["methods"]["Works"] = "GetWorks";
		$this->relations["lazyload"]["Works"] = "true";

		$this->dbAlias["created_at"] =  "datetime";
		$this->dbAlias["updated_at"] =  "datetime";
	}

	// >>> relations:
	public function GetTasks(){
		if($this->relations["properties"]["Tasks"] != null) return $this->relations["properties"]["Tasks"];
		$pk = $this->dbPk;
		$this->relations["properties"]["Tasks"] = TaskControlBase::GetWhere(array("user_id" => $this->$pk));
		return $this->relations["properties"]["Tasks"];
	}
	public function GetCreatedTasks(){
		if($this->relations["properties"]["CreatedTasks"] != null) return $this->relations["properties"]["CreatedTasks"];
		$pk = $this->dbPk;
		$this->relations["properties"]["CreatedTasks"] = TaskControlBase::GetWhere(array("creator_id" => $this->$pk));
		return $this->relations["properties"]["CreatedTasks"];
	}
	public function GetWorks(){
		if($this->relations["properties"]["Works"] != null) return $this->relations["properties"]["Works"];
		$pk = $this->dbPk;
		$this->relations["properties"]["Works"] = WorkControlBase::GetWhere(array("user_id" => $this->$pk));
		return $this->relations["properties"]["Works"];
	}

}

class UserControlBase extends MagratheaModelControl {
	protected static $modelName = "User";
	protected static $dbTable = "users";
}
?>